name: hello world

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  print-hello:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: helloworld
        run: echo "helloworld"

  goodbye:
    runs-on: ubuntu-latest
    steps:
      - name: goodbyeworld
        run: echo "goodbyeworld"